### PR TITLE
math-magician: Full website

### PR DESCRIPTION
**Pull request by silviatofana**
In this pull request I:

Created a website consisting of 3 pages: Home, Calculator, and Quote
Added my own styles to improve the look and feel
created route for every page
set navigation links for all 3 routes to be displayed on each page
used Use [React Router](https://reactrouter.com/) to make the routes work.
your review is welcome😄!

### CODE REVIEW

**Review by DammyShittu — CHANGES_REQUESTED** [review]
Hi @silviatofana,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### From the requirements, you are required to request a merge to the dev branch (Gitflow) not the main branch (Github Flow)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by silviatofana** [comment]
@DammyShittu  ok already compare with dev

**Comment by silviatofana** [comment]
@DammyShittu I need to submit again for another review?

**Comment by DammyShittu** [comment]
hi @silviatofana yes. generally, when a project is invalidated you request another review from the dashboard.

**Review by DammyShittu — APPROVED** [review]
Hi @silviatofana,

## APPROVED 🟢

✔️ Use of RRD for routing

Great implementation of all the requirements in this milestone. 👏

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by silviatofana** [comment]
@DammyShittu thanks

**Pull request merged**
